### ISSUE TITLE
OPA Policy

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#10]
Run OPA policy against all objects defined in a namespace
Input:
```yaml
namespace: *
objects:
- deployments
- pods
- service
opa:
- fromBundle: http://path/to/opa/bundle.zip
- fromConfigMap: policies
- fromValue: {...}
```

Metrics:
Passing / Failing objects
