### ISSUE TITLE
Nil pointer error when running postgres query from topology

### ISSUE THREAD

**Issue by yashmehrotra** [flanksource/canary-checker#1010]
```
    - icon: group
      lookup:
        postgres:
        - auth:
            password:
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: incident-commander-postgres
            username:
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: incident-commander-postgres
          connection: postgres://$(username):$(password)@postgres:5432/mission_control?sslmode=disable
          display:
            javascript: |
              JSON.stringify(results.rows.map(function(r) {return {name: r.name}}))
          name: Team names query
          query: SELECT name FROM teams
          results: -1
          test: {}
          transform: {}
      name: Teams
      type: lookup

```

```
2023-05-21T03:36:29.004Z        DEBUG   Running topology mission-control/mission-control depth=10
2023-05-21T03:36:29.004Z        DEBUG   Looking up components for Teams => <nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x4dd9001]

goroutine 2356 [running]:
github.com/flanksource/duty.GetSecretFromCache({0x0, 0x0}, {0xc0144831d0, 0xf}, {0xc014764400, 0x1b}, {0xc014743cf0, 0xd})
        /go/pkg/mod/github.com/flanksource/duty@v1.0.94/envvar.go:49 +0x181
github.com/flanksource/duty.GetEnvValueFromCache({0x0?, 0x0?}, {{0x0, 0x0}, {0x0, 0x0}, 0xc01475d440}, {0xc0144831d0?, 0x0?})
        /go/pkg/mod/github.com/flanksource/duty@v1.0.94/envvar.go:24 +0xb3
github.com/flanksource/canary-checker/api/context.(*Context).GetEnvValueFromCache(...)
        /app/api/context/context.go:55
github.com/flanksource/canary-checker/checks.GetAuthValues(0xc016e11200, 0xc016e367f0)
        /app/checks/common.go:66 +0x99
github.com/flanksource/canary-checker/checks.GetConnection(0xc016e11200, 0xc016e367e0, {0xc0144831d0, 0xf})
        /app/checks/common.go:27 +0x129
github.com/flanksource/canary-checker/checks.CheckSQL(0xc016e11200, {0x8853c88, 0xc0162c7500})
        /app/checks/sql.go:93 +0x2e6
github.com/flanksource/canary-checker/checks.(*PostgresChecker).Check(...)
        /app/checks/postgres.go:34
github.com/flanksource/canary-checker/checks.(*PostgresChecker).Run(0xc016e12710?, 0xc016e11200)
        /app/checks/postgres.go:28 +0x148
github.com/flanksource/canary-checker/checks.RunChecks(0xc016e11200)
        /app/checks/runchecks.go:22 +0x244
github.com/flanksource/canary-checker/pkg/topology.lookup(_, {_, _}, {0x0, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, ...})
        /app/pkg/topology/run.go:184 +0x213
github.com/flanksource/canary-checker/pkg/topology.mergeComponentLookup(0x7c74bc0?, 0xc016832780, 0xc014777400)
        /app/pkg/topology/run.go:31 +0xd7
github.com/flanksource/canary-checker/pkg/topology.lookupComponents(_, {{0xc
```
