### ISSUE TITLE
Duplicate Vue keys for http checks with same endpoint with different responseCodes

### ISSUE THREAD

**Issue by philipstaffordwood** [flanksource/canary-checker#105]
Duplicate `key`s are produced for `checkSets` for **http** checks in the GUI if same `endpoint` with different `responseCodes` is tested causing Vue updating issues.

e.g.

```YAML
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: http-miltple
spec:
  interval: 30
  http:
    - endpoint: https://httpstat.us/500
      thresholdMillis: 3000
      responseCodes: [500]
      responseContent: ""
      maxSSLExpiry: 7
    - endpoint: https://httpstat.us/500
      thresholdMillis: 3000
      responseCodes: [302]
      responseContent: ""
      maxSSLExpiry: 7
```
