### ISSUE TITLE
AWS / GCP / Azure CLI checks

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#1137]
i.e. use connections to run CLI commands

```yaml
exec:
 - connections
       aws: 
           connection: connection://aws/profile
       kubectl:
          connection: ...
   exec:  aws sts get-caller identity
```

Update both the minimal and full docker containers to install via https://github.com/alexellis/arkade: kubectl, stern, yq, jq, aws, azure, gcp CLI's
