### ISSUE TITLE
Canary auth not working as it should

### ISSUE THREAD

**Issue by loydbanks** [flanksource/canary-checker#1194]
I am currently using the canary-checker helm chart and I used Sealed secrets for the credentials of my database(Postgres database) but it fails to connect and gives the error

```
FAIL [postgres] staging/origin-staging/Postgres database duration=11  failed to query db: pq: password authentication failed for user "canary"
```
The folder in which  I have the canary in is called origin-staging and I can connect to the database via the postgres url. I tried not using secretKeyRef and just use the case below but it still fails and shows the user as "canary"

```
 auth:
    username:
      value: postgresadmin
    password:
      value: admin123
```

 Please help in fixing this issue

**Comment by yashmehrotra** [comment]
@loydbanks Can you share the entire crd spec that you are using ?

**Comment by loydbanks** [comment]
I'm not using any crd. Below is an example of what I have

```
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: origin-staging
  namespace: staging
spec:
  interval: 30
  postgres:
    - name: Postgres database
      auth:
        username:
          value: db-username
        password:
          value: db-password
      connection: "postgres://$(username):$(password)@db-host:5432/db-username"
      query: "SELECT 1;"
   ```
   Obviously replacing the db-username, and db-password with real credentials but it does not work. I tried using the secretKeyRef and valueFrom properties as well but it's not working

**Comment by yashmehrotra** [comment]
Can you try replacing `connection` with `url`

**Comment by loydbanks** [comment]
> Can you try replacing `connection` with `url`

I tried it with url and got the following error, it shows on my github workflow
```
The request is invalid: patch: Invalid value: "{\"apiVersion\":\"canaries.flanksource.com/v1\",\"kind\":\"Canary\",\"metadata\":{\"annotations\":{\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"apiVersion\\\":\\\"canaries.flanksource.com/v1\\\",\\\"kind\\\":\\\"Canary\\\",\\\"metadata\\\":{\\\"annotations\\\":{},\\\"name\\\":\\\"origin-staging\\\",\\\"namespace\\\":\\\"staging\\\"},\\\"spec\\\":{\\\"interval\\\":30,\\\"postgres\\\":[{\\\"auth\\\":{\\\"password\\\":{\\\"value\\\":\\\"db-password\\\"},\\\"username\\\":{\\\"value\\\":\\\"db-username\\\"}},\\\"name\\\":\\\"Postgres database\\\",\\\"query\\\":\\\"SELECT 1;\\\",\\\"url\\\":\\\"***db-host:5432/db-username\\\"}]}}\\n\"},\"creationTimestamp\":\"2023-07-19T10:17:36Z\",\"finalizers\":[\"canary.canaries.flanksource.com\"],\"generation\":6,\"managedFields\":[{\"apiVersion\":\"canaries.flanksource.com/v1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:finalizers\":{\".\":{},\"v:\\\"canary.canaries.flanksource.com\\\"\":{}}}},\"manager\":\"canary-checker\",\"operation\":\"Update\",\"time\":\"2023-07-19T10:17:36Z\"},{\"apiVersion\":\"canaries.flanksource.com/v1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:kubectl.kubernetes.io/last-applied-configuration\":{}}},\"f:spec\":{\".\":{},\"f:interval\":{},\"f:postgres\":{}}},\"manager\":\"kubectl-client-side-apply\",\"operation\":\"Update\",\"time\":\"2023-08-01T09:23:42Z\"},{\"apiVersion\":\"canaries.flanksource.com/v1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:status\":{\".\":{},\"f:checkStatus\":{\".\":{},\"f:/staging/origin-staging/postgres:Postgres database/Postgres database:fd3260c288d0946fa82af977ddb553fe\":{\".\":{},\"f:lastTransitionedTime\":{},\"f:latency1h\":{},\"f:uptime1h\":{}}},\"f:checks\":{\".\":{},\"f:Postgres database\":{}},\"f:errorMessage\":{},\"f:lastCheck\":{},\"f:lastTransitionedTime\":{},\"f:latency1h\":{},\"f:message\":{},\"f:observedGeneration\":{},\"f:status\":{},\"f:uptime1h\":{}}},\"manager\":\"canary-checker\",\"operation\":\"Update\",\"subresource\":\"status\",\"time\":\"2023-08-07T10:03:09Z\"}],\"name\":\"origin-staging\",\"namespace\":\"staging\",\"resourceVersion\":\"60564991\",\"uid\":\"5849b2b1-793b-4208-8433-2dd3f693b2bc\"},\"spec\":{\"interval\":30,\"postgres\":[{\"auth\":{\"password\":{\"value\":\"db-password\"},\"username\":{\"value\":\"db-username\"}},\"name\":\"Postgres database\",\"query\":\"SELECT 1;\",\"url\":\"***db-host:5432/username\"}]},\"status\":{\"checkStatus\":{\"/staging/origin-staging/postgres:Postgres database/Postgres database:fd3260c288d0946fa82af977ddb553fe\":{\"lastTransitionedTime\":\"2023-08-07T10:03:09Z\",\"latency1h\":\"rolling1h=20ms\",\"uptime1h\":\"0/167 0%\"}},\"checks\":{\"Postgres database\":\"0189b05f-5b50-1ce4-e707-52a12524815f\"},\"errorMessage\":\"\",\"lastCheck\":\"2023-08-07T10:03:09Z\",\"lastTransitionedTime\":\"2023-08-07T10:03:09Z\",\"latency1h\":\"20ms\",\"message\":\"\",\"observedGeneration\":6,\"status\":\"Failed\",\"uptime1h\":\"0/167 0%\"}}": strict decoding error: unknown field "spec.postgres[0].url"
```

**Comment by yashmehrotra** [comment]
What version of canary-checker and helm chart are you using ?

**Comment by moshloop** [comment]
This could also be an issue with a randomly generated password with non url safe chars, in which case you should url encode before putting into the secret (Logged https://github.com/flanksource/canary-checker/issues/1213 to make it possible to inline the urlencode) 

There is also a 5 minute cache for values looked up from configmap/secrets

**Comment by loydbanks** [comment]
> What version of canary-checker and helm chart are you using ?

I'm using a helm chart with version 1.0.26

**Comment by loydbanks** [comment]
Last known working version: 0.38.319

**Comment by moshloop** [comment]
@loydbanks try the following on the latest version:

```
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: origin-staging
  namespace: staging
spec:
  interval: 30
  postgres:
    - name: Postgres database
      username:
        value: db-username
      password:
        value: db-password
      url: "postgres://$(username):$(password)@db-host:5432/db-username"
      query: "SELECT 1;"
```
