### ISSUE TITLE
[bug] Canary-check: Pod: Issue with scheduling pods in case taints and tolerations using

### ISSUE THREAD

**Issue by msergg** [flanksource/canary-checker#1232]
In case creating pod check in example:

```
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: pod-check
spec:
  interval: 30
  pod:
    - name: golang
      spec: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: hello-world-golang
          namespace: default
          labels:
            app: hello-world-golang
        spec:
          containers:
            - name: hello
              image: quay.io/toni0/hello-webserver-golang:latest
      port: 8080
      path: /foo/bar
      scheduleTimeout: 20000
      readyTimeout: 10000
      httpTimeout: 7000
      deleteTimeout: 12000
      ingressTimeout: 10000
      deadline: 60000
      httpRetryInterval: 200
      expectedContent: bar
      expectedHttpStatuses: [200, 201, 202]
      priorityClass: canary-checker-priority
```

And using some configuration for node taints and toleration, 
we getting error, do not have possibility to schedule pod.

It is caused due to using logic configured in pod check
with next node logic as node selector in previous steps:
```
	pod.Spec.NodeSelector = map[string]string{
		"kubernetes.io/hostname": nodeName,
	}
```
So kube scheduler could not schedule pod to free untained instance

https://github.com/flanksource/canary-checker/blob/cc1c86306aa5013e670add2da43136bf6adf0eee/checks/pod.go#L92

Please remove this part or make it optional and configurable
```
	pod.Spec.NodeSelector = map[string]string{
		"kubernetes.io/hostname": nodeName,
	}
```
