### ISSUE TITLE
HTTP check - Use kubernetes serviceAccount (and token)

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#1241]
e.g. to Test hashicorp vault kubernetes auth (https://github.com/flanksource/canary-checker/issues/1053) 
```yaml
http:
  - url:  https://vault.example/v1/auth/kubernetes/login
    method: POST
    serviceAccountName: "default"
    body: |
        {
           "jwt": "$(TOKEN)",
           "role": "example-role"
        }
     test:
        expr: response.json.auth.client_token != ''
```

**Comment by adityathebe** [comment]
Can access token for a serviceAccount using `env`

```yaml
http:
  - url:  https://vault.example/v1/auth/kubernetes/login
    method: POST
    body: |
      {
        "jwt": "{{.kube_token}}",
        "role": "example-role"
      }
    test:
      expr: response.json.auth.client_token != ''
    env:
      - name: kube_token
        valueFrom:
          serviceAccount: my-service-account
```
