### ISSUE TITLE
HTTP - Support looking up values into headers and body

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#1335]
```yaml
http:
  - envFrom:
      - name: hello
        value: world
    templateBody: true
    body: | 
      { 
        "hello": "$(hello)"
      }
```
