### ISSUE TITLE
Add severity and owner/email 

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#136]
Add on dashboard icons on the severity and popup with owner/email details.
+ Filter on severity / owner
+ add severity / email details into the prometheus alerts

```
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: http-pass
spec:
  interval: 30
  description: "When this canary fails it means that either http.us is down (unknlikely) or there is an issue with upstream i internet connection"
  owner: networks
  severity: critical
  http:
    - endpoint: https://httpstat.us/200
      thresholdMillis: 3000
      responseCodes: [201, 200, 301]
      responseContent: ""
      maxSSLExpiry: 7
```
