### ISSUE TITLE
Webhook Check

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#1364]
```yaml
webhook:
   - name: # globally unique name for the webhook
      token: 
          name: 'token'. # validate this token from query params or headers
          valueFrom: ...
```

Create an endpoint `/webhook/{check_id}|{name}` if more than 1 matching webhook return an error

Normal transform functions are then used to extract metrics, or check details with the template vars:

- headers
- content
- json

Create an example of alertmanagers https://prometheus.io/docs/alerting/latest/configuration/#webhook_config
