### ISSUE TITLE
Update topology spec for properties

### ISSUE THREAD

**Issue by yashmehrotra** [flanksource/canary-checker#1378]
- Add lookup type option : valueLookup,  propertiesLookup and componentsLookup
- change from CanarySpec to LookupSpec

**Comment by moshloop** [comment]
```
- name: cpu
  lookups:
    - query: sum(node:node_num_cpu:sum)
   	  mapping:
         max: int(results[0].value
    - query:  '1000 * sum(rate(container_cpu_usage_seconds_total{container!=""{{.Values.prometheus.labels}}}[5m]))'
      connection: connection://{{ .Values.prometheus.connection }}
	  mapping:
          value: int(results[0].value
          headline: true
          unit: "'millicores'"
```
