### ISSUE TITLE
Change property fields (min, max, value, text) to Lookup types

### ISSUE THREAD

**Issue by yashmehrotra** [flanksource/canary-checker#1458]
```
property:
  text:
    valueString: <string>
    valueFloat: <float64> 
    lookupRef:
      postgres: <canary_spec>
   configLookup:
     class:
     type:
     tags:
```
