### ISSUE TITLE
ICMP Check

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#15]
**Input**:

```yaml
# If DNS, test connectivity for each returned record
endpoints: []
# max response time
thresholdMillis: 300
# max percentage packet loss
packetLossThreshold: 0.01
```

**Metrics** (per endpoint)
* latency
* packetLoss
