### ISSUE TITLE
Chart - Least Privileged RBAC

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#1507]
```yaml
rbac:
      # Whether to create cluster of namespaced scoped roles
      scope:  Cluster
     # for secret management with valueFrom
      tokenRequest: true
      secrets: true
      configmaps: true
      # for use with kubernetes resource lookups
      readAll: true
      # for pod and junit canaries
      podsCreateAndDelete: true
      # for pod canary
      ingressCreateAndDelete: true
      # for namespace canary
      namespaceCreateAndDelete: true
```
