### ISSUE TITLE
EC2 check failing

### ISSUE THREAD

**Issue by dabasvibhor** [flanksource/canary-checker#1543]
From the cluster:

`FAIL [ec2] cc/ec2-check/ec2-check duration=0  could not perform prerun check: not found, ResolveEndpointV2`

From the CLI:

`[ec2] default/ec2-check/ec2-check duration=3  could not perform prerun check: not found, ResolveEndpointV2`

Manifest used:
```
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: ec2-check
spec:
  interval: 30
  ec2:
    - name: ec2-check
      ami: ami-02cad064a29d4550c
      description: test instance
        accessKey:
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        secretKey:
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
      region: eu-west-1
      userData: |
        #!/bin/bash
        yum install -y httpd
        systemctl start httpd
        systemctl enable httpd
        usermod -a -G apache ec2-user
        chown -R ec2-user:apache /var/www
        chmod 2775 /var/www
        find /var/www -type d -exec chmod 2775 {} \;
        find /var/www -type f -exec chmod 0664 {} \;
      securityGroup: default
```
