### ISSUE TITLE
Kubernetes check failing

### ISSUE THREAD

**Issue by dabasvibhor** [flanksource/canary-checker#1545]
https://canarychecker.io/reference/kubernetes

```
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: kube-check
spec:
  interval: 30
  kubernetes:
    - namespace:
        name: canaries
      name: k8s-ready pods
      kind: Pod
      resource:
        labelSelector: control-plane=canary-checker
```

`The Canary "kube-check" is invalid: spec.kubernetes[0].namespace: Invalid value: "object": spec.kubernetes[0].namespace in body must be of type string: "object"`

However, it gets applied when changing the spec to 
```
  kubernetes:
    - namespace: canaries
      name: k8s-ready pods
      kind: Pod
      resource:
```
Now the canary checker logs say 

`Failed to watch *v1.Canary: failed to list *v1.Canary: json: cannot unmarshal string into Go struct field KubernetesCheck.items.spec.kubernetes.namespace of type v1.ResourceSelector`

Here is the CRD snippet for kubernetes check

```
Namespace:
  Description:  Namespace of the check
  Properties:
    Field Selector:
      Type:  string
    Label Selector:
      Type:  string
    Name:
      Type:  string
  Type:      string
```
