### ISSUE TITLE
JMeter check

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#157]
To run the check: https://jmeter.apache.org/usermanual/get-started.html#non_gui

https://jmeter.apache.org/usermanual/get-started.html#override

```yaml
jmeter:
   # -t
   jmx:
   # -t 
   jmxFrom:
     - configMap...
    # -J
   properties:
    # -D
   systemProperties:
 ```
