### ISSUE TITLE
Junit canary created via UI not running

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#1704]
https://incident-commander.demo.aws.flanksource.com/settings/canaries/018dc126-75d0-4ec4-6e39-d2b1a6242024

**Comment by yashmehrotra** [comment]
Fixed, the spec was wrong (schema wise)

Changed
```yaml
junit:
  - junit:
      - display:
          template: >
            ✅ {{.results.passed}} ❌ {{.results.failed}} in 🕑
            {{.results.duration}}

            {{  range $r := .results.suites}}

            {{- if gt (conv.ToInt $r.failed)  0 }}
              {{$r.name}} ✅ {{$r.passed}} ❌ {{$r.failed}} in 🕑 {{$r.duration}}
            {{- end }}

            {{- end }}
        name: login
        spec:
          containers:
            - command:
                - /run-playwright.sh
              image: docker.io/flanksource/flanksource-ui-playwright-canary:latest
              name: playwright
        testResults: /tmp/
    schedule: "@every 3m"

```
to 

```yaml
junit:
  - display:
      template: >
        ✅ {{.results.passed}} ❌ {{.results.failed}} in 🕑
        {{.results.duration}}

        {{  range $r := .results.suites}}

        {{- if gt (conv.ToInt $r.failed)  0 }}
          {{$r.name}} ✅ {{$r.passed}} ❌ {{$r.failed}} in 🕑 {{$r.duration}}
        {{- end }}

        {{- end }}
    name: login
    spec:
      containers:
        - command:
            - /run-playwright.sh
          image: docker.io/flanksource/flanksource-ui-playwright-canary:latest
          name: playwright
    testResults: /tmp/
schedule: "@every 3m"

```
