### ISSUE TITLE
Prometheus checks / lookups - Add auth options

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#1718]
```yaml

prometheus:
   - url: http://prometheus
      connection: 
      headers: 
      auth:
          basic:
             username:
                value:
             password:
                value:
          bearer:
              value
          oauth2
```
