### ISSUE TITLE
Canary failing when job in progress

### ISSUE THREAD

**Issue by dabasvibhor** [flanksource/canary-checker#1754]
<img width="391" alt="image" src="https://github.com/flanksource/canary-checker/assets/55124746/fc490f20-1015-4962-99c5-b94552393231">

Canary spec:

```
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: dbt-cronjob-check
  annotations:
      argocd.argoproj.io/sync-wave: "2"
spec:
  interval: 5
  kubernetes:
    - name: major-minor-reconcile
      kind: Job
      ready: true
      namespaceSelector:
        name: dbt
      kubeconfig:
          name: internal-apps
          valueFrom:
            secretKeyRef:
              name: bcb-group-internal-apps-app-cluster-kubeconfig
              key: kubeconfig
```
