### ISSUE TITLE
When using db.external service selectors overlap

### ISSUE THREAD

**Issue by krohrsb** [flanksource/canary-checker#1765]
When opting to use the external db:

```yaml
  db:
    external:
      enabled: true
      create: true
```

The `selectorLabels` used on the `canary-checker` service match both the canary-checker pod as well as the postgres-db pod. This causes issues when the canary-checker-ui attempts to connect to its backend (as it sometimes gets routed to postgres).

The selectors need to be unique.

Example postgres pod labels:

```
labels:
    app: postgresql
    app.kubernetes.io/instance: canary
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: canary-checker
    app.kubernetes.io/version: 1.0.257
    apps.kubernetes.io/pod-index: '0'
    control-plane: canary-checker
    controller-revision-hash: postgresql-648ccc45fb
    helm.sh/chart: canary-checker-1.0.257
    statefulset.kubernetes.io/pod-name: postgresql-0
```

And the selectorLabels for the canary-checker service:

```
  selector:
    app.kubernetes.io/instance: canary
    app.kubernetes.io/name: canary-checker
    control-plane: canary-checker
```
