### ISSUE TITLE
Http Check - Check all records returned by DNS

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#1780]
e.g. To test all the pods in a headless service or from a SRV record

```yaml

http:
   - url: http://host.com
      dns:
          type: SRV # defaults to A
          mode: all # Which dns record to the send the request to:  `first` (default), `random`, `all`

```
