### ISSUE TITLE
Topology -  use catalog traversal for building a topology

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#1816]
```yaml

config:
   type: Kubernetes::HelmRelease
forEach:
relationships:
     - type: Kubernetes::Pod
        direction: outgoing

```
