### ISSUE TITLE
unsupported CronJob GVK: batch/v1, Kind=CronJob

### ISSUE THREAD

**Issue by dabasvibhor** [flanksource/canary-checker#1818]
`error getting resource health (CronJob/v/example-cronjob): unsupported CronJob GVK: batch/v1, Kind=CronJob`

```
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: vibhor-testing-cronjob
  namespace: canaries
spec:
  interval: 5
  kubernetes:
    - name: vibhor-testing-cronjob
      kind: CronJob
      namespaceSelector:
        name: v
      resource:
        name: example-cronjob
      ready: true
```

https://incident-commander.demo.aws.flanksource.com/health?hidePassing=false&labels=%257B%257D&query=&layout=table&timeRange=1h&checkId=018f33e1-cb1a-511b-52f5-621086f3b3f8
