### ISSUE TITLE
Allow passing a CA certificate to http checks

### ISSUE THREAD

**Issue by fullykubed** [flanksource/canary-checker#1889]
When using a private x.509 CA for HTTPS endpoints (i.e., with Kubernetes webhooks), http checks cannot currently be used as there is no way to pass in a CA to enable the TLS connection to be established.

It would be nice to be able to configure this in the connection settings to enable validation of these endpoints.

**Comment by adityathebe** [comment]
https://docs.flanksource.com/canary-checker/reference/http#tls-config


```yaml
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: http-check
spec:
  interval: 30
  http:
    - name: http pass response 200 status code
      url: https://httpbin.demo.aws.flanksource.com/status/200
      tlsConfig:
        ca:
          valueFrom:
            secretKeyRef:
              name: ca-cert
              key: ca.pem
```

closing this @moshloop
