### ISSUE TITLE
Pod Check - Junit support

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#190]
When specified, 

1) Create and (reuse) a PV, and inject it into the pod to schedule
2) Once the pod completes, check the testResults folder for Junit formatted files, and use

```yaml
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: junit
spec:
  interval: 30
  junit:
    - name: junit
       testResults: /tmp/junit-*xml
       minPass: 1
       maxFail: 0
       maxSkip: 0
       timeout:
       spec: 
          ... //PodSpec      
```
