### ISSUE TITLE
Rate limiting / Circuit Breakers

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#1945]
For canaries that are slow to run (i.e.. could be using expensive resources / queries) allow specifying rate limits

```
rateLimit: duration_95 > 1000 ?  '1/5m' : duration_95 > '10000' ? '1/30m' : duration_95 > '30000' : '1/1h'
circuitBreaker:
    - expr: duration_95 > 5000
       for: 60m
```
