### ISSUE TITLE
[BUG] Owner is not displayed

### ISSUE THREAD

**Issue by DanielCastronovo** [flanksource/canary-checker#1985]
When i set a owner on a Canary CR, the UI doesn't print it.
![image](https://github.com/user-attachments/assets/0b6764be-3d35-4f84-9ec4-e45db5b8defb)

```
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: prometheus-check
spec:
  owner: Infra
  severity: high
  interval: 30
  prometheus:
    - url: http://prometheus-operator-prometheus.kube-system.svc.cluster.local:9090
      query: kubernetes_build_info{job!~"kube-dns|coredns"}
      display:
        template: "{{ (index .results 0).git_version }}"
      test:
        template: "true"
      name: test
```
