### ISSUE TITLE
Docker Image Pull

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#2]
Test that a docker image can be pulled

**Input**:

```yaml
image: docker.io/busybox
username: 
password:
expectedDigest:  abcdef123
expectedSize: 200m
```

**Metrics** (per endpoint)
* pull_time
* layers
* size
