### ISSUE TITLE
Kubernetes Resource - Display Messages Not Working

### ISSUE THREAD

**Issue by dmorrowjc** [flanksource/canary-checker#2086]
The display formatting for Kubernetes Resource checks does not appear to be working. 

If I setup a basic Kubernetes check and format the display, it seems to work fine:
```
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: kube-system-checks
spec:
  interval: 30
  kubernetes:
    - namespace: kube-system
      name: kube-system
      kind: Pod
      resource:
        labelSelector: k8s-app=kube-dns
      namespaceSelector:
        name: kube-system
      display:
        expr: |
          dyn(results).all(x, k8s.isHealthy(x))
```

However, if I use a check like this within the Kubernetes Resource check, nothing is displayed:
```
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: daemonset-checks
  namespace: canary-checker
spec:
  schedule: "@every 1m"
  kubernetesResource:
    - name: daemonset
      namespace: canary-checker
      description: "Create a daemonset and check that it's healthy"
      waitFor:
        expr: 'dyn(resources).all(r, k8s.isHealthy(r))'
        interval: 60s
        timeout: 5m

      resources:
        - apiVersion: apps/v1
          kind: DaemonSet
          metadata:
            name: canary-daemonset
            namespace: canary-checker
            labels:
              app: canary-daemonset
          spec:
            selector:
              matchLabels:
                app: canary-daemonset
            template:
              metadata:
                labels:
                  app: canary-daemonset
              spec:
                containers:
                - name: pause
                  image: "gcr.io/google-containers/pause:3.2" 

      checks:
        - kubernetes:
            - name: canary-daemonset
              namespace: canary-checker

              kind: DaemonSet
              healthy: true
              namespaceSelector:
                name: canary-checker
              display:
                expr: |
                  dyn(results).all(x, k8s.isHealthy(x))
              test:
                expr: dyn(results).all(x, k8s.isHealthy(x))
```
![image](https://github.com/user-attachments/assets/5b384a18-da2e-4445-a2c7-3e90a7585bd0)

If I instead try to configure the display message for the Kubernetes Resource check at the scope of the Canary, I am able to do so...
```
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: daemonset-checks
  namespace: canary-checker
spec:
  schedule: "@every 1m"
  kubernetesResource:
    - name: daemonset
      namespace: canary-checker
      description: "Create a daemonset and check that it's healthy"
      waitFor:
        expr: 'dyn(resources).all(r, k8s.isHealthy(r))'
        interval: 60s
        timeout: 5m

      resources:
        - apiVersion: apps/v1
          kind: DaemonSet
          metadata:
            name: canary-daemonset
            namespace: canary-checker
            labels:
              app: canary-daemonset
          spec:
            selector:
              matchLabels:
                app: canary-daemonset
            template:
              metadata:
                labels:
                  app: canary-daemonset
              spec:
                containers:
                - name: pause
                  image: "gcr.io/google-containers/pause:3.2" 

      display:
        expr: string("a test display")                  

      checks:
        - kubernetes:
            - name: canary-daemonset
              namespace: canary-checker

              kind: DaemonSet
              healthy: true
              namespaceSelector:
                name: canary-checker
              test:
                expr: dyn(results).all(x, k8s.isHealthy(x))
```
![image](https://github.com/user-attachments/assets/54bd1f33-4998-448c-855d-8806d568cef9)

...however, I am not able to access any meaningful information about my resources:
```
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: daemonset-checks
  namespace: canary-checker
spec:
  schedule: "@every 1m"
  kubernetesResource:
    - name: daemonset
      namespace: canary-checker
      description: "Create a daemonset and check that it's healthy"
      waitFor:
        expr: 'dyn(resources).all(r, k8s.isHealthy(r))'
        interval: 60s
        timeout: 5m

      resources:
        - apiVersion: apps/v1
          kind: DaemonSet
          metadata:
            name: canary-daemonset
            namespace: canary-checker
            labels:
              app: canary-daemonset
          spec:
            selector:
              matchLabels:
                app: canary-daemonset
            template:
              metadata:
                labels:
                  app: canary-daemonset
              spec:
                containers:
                - name: pause
                  image: "gcr.io/google-containers/pause:3.2" 

      display:
        expr: dyn(results).map(x, k8s.getHealth(x).message)

      checks:
        - kubernetes:
            - name: canary-daemonset
              namespace: canary-checker

              kind: DaemonSet
              healthy: true
              namespaceSelector:
                name: canary-checker
              test:
                expr: dyn(results).all(x, k8s.isHealthy(x))
```

![image](https://github.com/user-attachments/assets/d59022d8-7f61-4f93-800f-1f60f7206a6d)

I'm also generally struggling to figure out which variables are available to me when using CEL expressions. From examples in the docs I can infer that `resources` is available in the `waitFor` expression and `results` should be available in the `display` expression, but it's unclear if those are all the variables that I can reference. In my example with a DaemonSet above I can't tell if I'm using the wrong variable or if the display itself is buggy because all I can see is an empty map getting returned.
