### ISSUE TITLE
HTTP check env var logging exposes potential secret values

### ISSUE THREAD

**Issue by mtweten** [flanksource/canary-checker#2166]
When using environment variables to template body payloads (described in https://canarychecker.io/reference/http#template-body-variables), if any of the env variables are sourced from a secret, the secret value will be leaked in the canary-checker logs due to this info level logging statement: https://github.com/flanksource/canary-checker/blob/master/checks/http.go#L203

Example check:

```
---
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: test-login
spec:
  interval: 30
  http:
    - name: Login Check
      endpoint: https://some.site/login
      env:
        - name: password
          valueFrom:
            secretKeyRef:
              name: secret
              key: password
      responseCodes: [200]
      templateBody: true
      body: |
        {
          "user": "admin",
          "password": "{{.password}}"
        }
```
This results in a log statement like the following:
```
{"time":"2024-09-24T20:38:25.005626351Z","level":"INFO","msg":"password => <actual-secret-value> err:<nil>","logger":"canary[default/test-login]"}
```
