### ISSUE TITLE
EC2 Instance Check

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#217]
```yaml
ec2:
  accessKey: envFrom
  secretKey: envFrom
  #optional
  assumeRole: 
  # name, id or blank (first vpc in account)
  vpc: 
  region:
  # name or id of a webserver listening on 80:
  ami:
  availabilityZone:
  # optional, if empty choose first subnet in the az
  subnet:
  #optional
  instanceProfile:
  # optional
  userData:
  securityGroups: []
  # optional
  volumeSize:
  # 1 or more instance types to try and launcc
  instanceType:
    -
 launchTimeout:
 canary:
    - http:
         url: "http://{{.privateIpAddress}}"
 
         
```
