### ISSUE TITLE
HTTP - Support Endpoint from Value

### ISSUE THREAD

**Issue by oc-christopher-billett** [flanksource/canary-checker#2178]
Currently the endpoint cannot be pulled form a valueFrom. When storing secure endpoints such as those that use API tokens in the parameters and not the headers means that the endpoint need to be placed in code in plain text.

It would be more secure to allow the endpoint to be pulled form a secret.

**Comment by moshloop** [comment]
hi @oc-christopher-billett 

This should work in the latest builds:

```yaml
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: http-basic-auth-url
spec:
  http:
    - name: test-url-via-env
      # The URL can be templated from arbritrary values using the env field and $(.) syntax
      url: $(.url)
      env:
        - name: url
          value: https://hello:world2@httpbin.demo.aws.flanksource.com/basic-auth/hello/world2
```
