### ISSUE TITLE
check.labels should be added to prometheus_metrics

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#2227]
```
  http:
    - url: https://httpbin.demo.aws.flanksource.com/status/200
      name: http-pass-single
      labels:
        check1: http-200
```

`canary_check_info{canary_name="http-checks",canary_namespace="test2",endpoint="https://httpbin.demo.aws.flanksource.com/status/200",key="01927a78-f161-2f8d-252a-1f2d8aa2e159",name="http-pass-single",owner="",severity="",type="http", check1="http-200"} 0`
