### ISSUE TITLE
CRD unknown field

### ISSUE THREAD

**Issue by oc-christopher-billett** [flanksource/canary-checker#2287]
@yashmehrotra  - Following on from #2278 the below error is seen on 1.0.1-beta-38

`Error from server (BadRequest): error when creating "myDomain.yaml": Canary in version "v1" cannot be handled as a Canary: strict decoding error: unknown field "spec.http[0].metrics[0].labels[0].name", unknown field "spec.http[0].metrics[0].labels[0].valueExpr", unknown field "spec.http[0].metrics[0].labels[1].name", unknown field "spec.http[0].metrics[0].labels[1].valueExpr"`

```
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: myDomain
spec:
  schedule: "@every 1m"
  http:
    - name: myDomain
      url: https://myDomain.com
      thresholdMillis: 20000
      responseCodes: [201, 200, 301]
      metrics:
        - name: canary_checker_custom_http_status
          type: gauge
          value: "200"
          labels:
            - name: check_name
              valueExpr: check.name
            - name: url
              valueExpr: check.url
```
