### ISSUE TITLE
Support for VolumeMounts in JUnit check

### ISSUE THREAD

**Issue by LarsFronius** [flanksource/canary-checker#2318]
Hi,

Thanks for the great tool first of all!

We are just starting out to adopt it and I have an issue utilizing volumeMounts with JUnit checks - I am not sure if this is generally supported, but the CRD generally allows it.

My use case is that I'd like to have a single playwright base image, shared among a set of tests. The tests shall be deployed into e.g. a config map and mounted in the concrete tests.

This is my canary custom resource:
```yaml
apiVersion: canaries.flanksource.com/v1
kind: Canary
spec:
  interval: 60
  junit:
    - display:
        template: >
          ✅ {{.results.passed}} ❌ {{.results.failed}} in 🕑
          {{.results.duration}}

          {{  range $r := .results.suites}}

          {{- if gt (conv.ToInt $r.failed)  0 }}

          {{$r.name}} ✅ {{$r.passed}} ❌ {{$r.failed}} in 🕑 {{$r.duration}}

          {{- end }}

          {{- end }}
      name: playwright-example-com
      spec:
        containers:
          - image: my-playwright-image
            name: playwright
            volumeMounts:
              - mountPath: /playwright/tests
                name: spec-file
        volumes:
          - configMap:
              name: playwright-spec-example-com
            name: spec-file
      testResults: /tmp/
  replicas: 1
```

Config map may look something like this
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: playwright-spec-example-com
data:
  example-com.spec.ts: |-
    import { test, expect } from '@playwright/test';

    test('ensure menu clickable', async ({page}) => {
        await page.goto('https://www.foobar.com');
        await page.getByRole('link', { name: 'Foo', exact: true }).first().click();
    });
```

The individual pods that are being created by canary-checker to execute the tests appear to completely lack the volumes und volume mounts though:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: playwright-example-com-kmmws
  labels:
    canary-checker.flanksource.com/check: junit-check-playwright-example-com-....
  selfLink: xxxx
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-11-05T11:20:26Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-11-05T11:20:27Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-11-05T11:20:27Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2024-11-05T11:20:23Z'
  hostIP: xxxx
  podIP: xxxx
  podIPs:
    - ip: xxxx
  startTime: '2024-11-05T11:20:23Z'
  initContainerStatuses:
    - name: playwright
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: '2024-11-05T11:20:24Z'
          finishedAt: '2024-11-05T11:20:25Z'
          containerID: >-
            containerd://13dd7c7dca6967690667a6e1680bc6167260ef5536ff95a919c00d8958a7a3da
      lastState: {}
      ready: true
      restartCount: 0
      image: my-playwright-image
      imageID: xxxxx
      containerID: xxxxx
      started: false
  containerStatuses:
    - name: junit-results
      state:
        running:
          startedAt: '2024-11-05T11:20:26Z'
      lastState: {}
      ready: true
      restartCount: 0
      image: docker.io/library/ubuntu:latest
      imageID: >-
        docker.io/library/ubuntu@sha256:99c35190e22d294cdace2783ac55effc69d32896daaa265f0bbedbcde4fbe3e5
      containerID: >-
        containerd://c515fdf8bd19280b06ac5eafe920f7402a8be65e209ec7e574adfb6388b1e6d5
      started: true
  qosClass: BestEffort
spec:
  volumes:                                <-- where I'd expect my volume definition to be added
    - name: junit-results
      emptyDir: {}
    - name: kube-api-access-xvqx2
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  initContainers:
    - name: playwright
      image: my-playwright-image
      resources: {}
      volumeMounts:                             <-- where I'd expect my volume mount to appear
        - name: junit-results
          mountPath: /tmp
        - name: kube-api-access-xvqx2
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
  containers:
    - name: junit-results
      image: ubuntu
      args:
        - bash
        - '-c'
        - "\n\t\t\t\tfunction wait() {\n\t\t\t\t\tuntil [ -f /tmp/junit-results/done ]\n\t\t\t\t\tdo\n\t\t\t\t\t\t\techo \"Waiting for done\"\n\t\t\t\t\t\t\tfind /tmp/junit-results\n\t\t\t\t\t\t\tsleep 1\n\t\t\t\t\tdone\n\t\t\t\t}\n\t\t\t\texport -f wait\n\t\t\t\ttimeout 60s bash -c wait\n\t\t\t\texit 0\n\t\t\t\t"
      resources: {}
      volumeMounts:
        - name: junit-results
          mountPath: /tmp/junit-results
        - name: kube-api-access-xvqx2
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
  restartPolicy: Never
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: xxx
  securityContext: {}
  imagePullSecrets:
    - name: image-pull-secret
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
```

Curious if I am missing something or if this is generally not supported?
What do you think about the use case of not baking all tests into the image, but rather share an image among various tests and only mount the individual tests per check?
