### ISSUE TITLE
HTTP / Prometheus - Kube Proxy

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#2349]
Provide an option to proxy http / prometheus requests via kubernetes API 

```yaml
- http: 
     # hostname is only used for setting Host: header
     url: http://prometheus.svc
     proxy:
       kubernetes:
           namespace: prometheus
           service:
                name:
                selector: 
           pod:
                selector
           port: 9090          
           kubeconfig:
                value: ...
```
