### ISSUE TITLE
S3 Bucket Scan

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#24]
A canary that can be used to check that backups are being made and that they are non-empty

**Input**:

```yaml
bucket:
accessKey:
secretKey:
endpoint:
objectPath: # glob path to restricy matches to a subet
readWrite: false
maxAge: # maximum allowed age of matched objects
minSize: # min size of of most recent matched object
```
**Output**: Pass/Failnvalid

**Metrics**:
* Total Size
* Object Count
* Last write time
