### ISSUE TITLE
error message on the crd should be removed when the canary passes

### ISSUE THREAD

**Issue by adityathebe** [flanksource/canary-checker#2468]
isHealthy treats this as unhealthy

![Image](https://github.com/user-attachments/assets/6d17ddd7-55c1-4be3-b63d-10004b8b50f1)

```
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  uid: 51e75298-b421-4765-abc3-3d7c9005562c
  name: canary-checker-helm-chart-embedded-persisted
  labels:
    kustomize.toolkit.fluxcd.io/name: canary-checker-canaries
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  namespace: canary-checker
  finalizers:
    - canary.canaries.flanksource.com
  creationTimestamp: 2025-02-27T14:55:52Z
spec:
  replicas: 1
  schedule: "@every 2h"
  kubernetesResource:
    - name: canary-checker-embedded-persisted
      checks:
        - http:
            - body: OK
              name: health-check-embedded-persisted
              endpoint: http://canary-checker.canary-checker-persisted.svc:8080/health
              responseCodes:
                - 200
      waitFor:
        timeout: 1m
        interval: 5s
      namespace: canary-checker
      resources:
        - kind: HelmRelease
          spec:
            chart:
              spec:
                chart: canary-checker
                version: v1.x.x-beta
                sourceRef:
                  kind: HelmRepository
                  name: flanksource
                  namespace: canary-checker-persisted
            values:
              db:
                embedded:
                  persist: true
                  storageClass: premium-rwo
              flanksource-ui:
                enabled: false
              serviceAccount:
                rbac:
                  clusterRole: false
              canaryNamespace: canary-checker-persisted
            interval: 5m
            targetNamespace: canary-checker-persisted
          metadata:
            name: canary-checker-embedded-persisted
            namespace: canary-checker
          apiVersion: helm.toolkit.fluxcd.io/v2
      description: Deploy canary-checker via HelmRelease
      checkRetries:
        delay: 5s
        timeout: 3m
        interval: 2s
      staticResources:
        - kind: Namespace
          metadata:
            name: canary-checker-persisted
          apiVersion: v1
        - kind: HelmRepository
          spec:
            url: http://flanksource.github.io/charts
            interval: 1h
          metadata:
            name: flanksource
            namespace: canary-checker-persisted
          apiVersion: source.toolkit.fluxcd.io/v1
status:
  checks:
    canary-checker-embedded-persisted: 019547e8-2b98-0585-b315-ff79035280ce
  status: Passed
  message: "health-check-embedded-persisted: "
  replicas: 1
  checkStatus:
    019547e8-2b98-0585-b315-ff79035280ce: {}
  errorMessage: "error in evaluating wait for:
    canary-checker/HelmRelease/canary-checker-embedded-persisted: not ready"
```
