### ISSUE TITLE
Crashloopback when configuration can't be read

### ISSUE THREAD

**Issue by ChrisMcKee** [flanksource/canary-checker#2477]
flanksource/canary-checker:v1.1.1-beta.28

Adding this config 

```
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: elasticsearch-uk-dev
  namespace: monitoring
spec:
  schedule: "@every 5m"
  elasticsearch:
    - url: https://someawsaddr.eu-west-2.es.amazonaws.com
      name: elasticsearch-gb-test
      description: Elasticsearch GB Test
      index: index
      query: |
        {
          "query": {
            "term": {
              "system.role": "api"
            }
          }
        }
      results: 1
      username:
        valueFrom:
          secretKeyRef:
            name: canary-check-elasticsearch-gb-dev
            key: username
      password:
        valueFrom:
          secretKeyRef:
            name: canary-check-elasticsearch-gb-dev
            key: password
```

Killed the canary-check pod leaving it in a loop 

```
panic: interface conversion: interface {} is nil, not map[string]interface {}
goroutine 285 [running]:
github.com/flanksource/canary-checker/checks.(*ElasticsearchChecker).Check(0x0?, 0xc020dff208, {0x8b86a40?, 0xc020f40bf0?})
	/app/checks/elasticsearch.go:72 +0xd2e
github.com/flanksource/canary-checker/checks.(*ElasticsearchChecker).Run(0xc345e00, 0xc020dff208)
	/app/checks/elasticsearch.go:26 +0x167
github.com/flanksource/canary-checker/checks.RunChecks(0xc020dff208)
	/app/checks/runchecks.go:127 +0x624
github.com/flanksource/canary-checker/pkg/jobs/canary.CanaryJob.Run({{{{0x0, 0x0}, {0x0, 0x0}}, {{0xc01db3f780, 0x1b}, {0x0, 0x0}, {0xc01dbd2900, 0xa}, ...}, ...}, ...}, ...)
	/app/pkg/jobs/canary/canary_jobs.go:104 +0xa85
github.com/flanksource/duty/job.(*Job).Run(0xc01dae9080)
	/go/pkg/mod/github.com/flanksource/duty@v1.0.873/job/job.go:438 +0x1502
created by github.com/flanksource/duty/job.(*Job).AddToScheduler.func1 in goroutine 130
	/go/pkg/mod/github.com/flanksource/duty@v1.0.873/job/job.go:622 +0x56
```
