### ISSUE TITLE
canary-checker for MySQL doesn't work

### ISSUE THREAD

**Issue by JCL38-ORANGE** [flanksource/canary-checker#2561]
Hello,

Thanks for your product.
I configure a canary in order to check my mariadb cluster like this : 
```
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
  name: mariadb-check-test
spec:
  schedule: '@every 5s'
  mysql:
    - url: mysql://$(username):$(password)@tcp(my-service.my-namespace.svc.cluster.local:3306)/information_schema
      name: mariadb ping check
      username:
        value: my-username
      password:
        value: my-password
      query: SELECT 1
```

I always face with the same error :
```
errorMessage: 'failed to query db: Error 1045 (28000): Access denied for user ''mysql''@''10.16.124.95''
```
I don't understand why it complains about the "mysql" user. Is it generic ?  

I create the user with the following commands : 
```
CREATE USER 'my-username'@'%' IDENTIFIED BY 'my-password';
grant all privileges on *.* to 'my-username'@'%' with grant option;
flush privileges;
```

I can connect to the database with my user with other tool like grafana datasource (remotely mode like canary checker).

It works like a charm for postgres and mongodb.
Maybe there is a problem with the https://github.com/go-sql-driver/mysql
Thanks in advance for your help.
Jean-Christophe.
