### ISSUE TITLE
Alert Manager Check

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#273]
Create a check that will query an alertmanager cluster for firing alerts, filter them down and then emit a pkg.CheckResult for each firing alert.

```yaml:
alertManager:
    - url:
       selector:
          severity: high
       alerts: 
          - BusinessCriticial*
       ignore:
          - Kube.*
```
