### ISSUE TITLE
Github Actions 

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#282]
```yaml

github:
    repo: flanksource/canary-checker
    action:  Build # optional name/regex of build
    status: # optional status
    branch:
      - main
    thresholdMillis: 
    test:
       junitArtifacts:
       annotations
```
