### ISSUE TITLE
Azure Devops

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#283]
This is similar to https://github.com/flanksource/config-db/blob/main/scrapers/azure/devops/pipelines.go, but rather than extracting all of the config, we pass the check if the most recent matched build has passed. 

```yaml
azureDevops:
    project: flanksource/canary-checker
    pipeline:  Build # optional name/regex of pipeline name
    variables: {} # match pipeline variables       
    branch:
      - main
    thresholdMillis: # maximum runtime of the build, after which it is considered unhealthy (optional)
```
