### ISSUE TITLE
Cloudwatch

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#286]
```yaml
cloudwatch:
     access,secretKey,region,assumeRole,accountId 
     filter:
        actionPrefix:
        alarmPrefix:
        alarms: []
        state: 
```
