### ISSUE TITLE
Circuit Breaker for long running checks

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#296]
Prevent health checks causing an issue on the services they monitor

```yaml
spec:
     circuitBreaker:
            avgDuration: 5m 
            count: 3 # trip if the last 3 checks average more than 5m ea.
            reset: 1h # stop running checks for 1h, if unspecified breaker needs to be manually turned back on
```
