### ISSUE TITLE
Merge pod + namespace checks into single k8s check

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#309]
```yaml

kubernetes:
   - resources: [] # e.g pod's or namespaces to deploy
     checks:
       - name: http-ingress-check # a ref to another canary which will run against the resources deployed
```
