### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#341]
Instead of 
```yaml
spec:

      http:
          - endpoint: http://url1
            auth:
                username: 
                   value: "user"
                password:
                   value: "pass"
          - endpoint: http://url2
             auth:
                username: 
                   value: "user"
                password:
                   value: "pass"
```

```yaml
spec:
    defaults
       auth:
          username: 
             value: "user"
          password:
             value: "pass"
      http:
          - endpoint: http://url1
          - endpoint: http://url2
```
