### ISSUE TITLE
JUnit Result Mode

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#358]
```yaml
resultMode: junit
http:
  - (1 of 100 checks)
```

When specified, don't emit a result per check, emit a single result as a junit test result
