### ISSUE TITLE
AWS Config Rules check

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#362]
```yaml
awsConfig:
     query:
     aggregatorName:
     *AWSConnection
```

when an aggegrator is specified use: SelectAggregateResourceConfig otherwise use SelectResourceConfig
