### ISSUE TITLE
Check Extractor

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#372]
For checks that can return multiple rows (Prometheus, SQL, HTTP,  etc..) provide a mechanism to extract additional checks from the results. 

```yaml
extract:
   rows:  results.items
   name: # expr
   description: # expr
   icon: # expr
   duration: # expr
   statues: # expr
```
