### ISSUE TITLE
Elasticsearch check

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#383]

**Comment by moshloop** [comment]
```yaml
elasticsearch:
    url: http://elasticsearch
    auth: ...
    query:  http_status_code: 500
```
