### ISSUE TITLE
Kubernetes Generic Check

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#436]
```yaml
kubernetesResource:
        
    - name: deploy a pod and check that it is accessible via ingress
       staticResources: # are deleted when the canary is deleted
         - Ingress spec
         - svc spec
       resources: # deleted after the check
         - A pod spec
       waitForReady: true # wait for resources to be ready before running checks
       timeout: 10m
       testResults: # extract test results from running pods
            -  path: /test/junit.xml
                type: junit # default
                pod:
                    name: {{.resources[0].metadata.name
                    # selector:
       checks:
         - http:
             url: {{.staticResources[0].ingress.spec.hostname }}             
```

Successor to pod, namespace jmeter and junit checks 

Work started here: https://github.com/flanksource/canary-checker/pull/368
