### ISSUE TITLE
Add a option in helmchart for servicemonitor

### ISSUE THREAD

**Issue by Kaitou786** [flanksource/canary-checker#479]
Currently, we include the service monitor object along with the canary checker as part of the base kustomize.  Some might not be using prometheus in the first place. The inclusion of service monitor should be optional with the helm charts values... with `prometheus=true`.

**Comment by Kaitou786** [comment]
As part of segregating the ServiceMonitor. the prometheus rule for canary checker should also be added:
```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: canary-checker-rules
spec:
  groups:
    - name: canary-severity
      rules:
        - alert: PostgresHeartbeatDown
          annotations:
            message: Postgres {{ $labels.exported_endpoint }} is down
          expr: canary_check{type="postgres"} > 0
          for: 5m
          labels:
            severity: page

        - alert: CanaryPodFailed
          expr: canary_check{type="pod"} > 0
          for: 15m
          labels:
            severity: page
          annotations:
            message: Failed to schedule and serve a pod for 15m

        - alert: CanaryImagePullFailed
          expr: canary_check{type=~"containerdPull|dockerPull"} > 0
          for: 5m
          labels:
            severity: page
          annotations:
            message: Failed to pull canary docker image

        - alert: CanaryFailed
          expr: canary_check{type!~"pod|postgres|containerdPull|dockerPull",$labels.severity="critical"} > 0
          for: 15m
          labels:
            severity: critical
          annotations:
            message: Canary {{ $labels.type }}/{{ $labels.name }} failing
        - alert: CanaryFailedWarning
          expr: canary_check{type!~"pod|postgres|containerdPull|dockerPull",$labels.severity!="critical"} > 0
          for: 15m
          labels:
            severity: warning
          annotations:
            message: Canary {{ $labels.type }}/{{ $labels.name }} failing
   ```
