### ISSUE TITLE
S3 Bucket test

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#5]
**Input**:

```yaml
bucket:
accessKey:
secretKey:
endpoint:
objectPath:
readWrite: false
```
**Output**: Pass/Failnvalid

**Metrics**:
* Lookup time
* List / Update / Read
*
