### ISSUE TITLE
Authentication - Switch to map[string]EnvVarSource

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#509]
Authentication is currently using for username and password only - But there are scenarios where it is useful to use if for more e.g. Database hostname or database name etc.. 

e.g.

```yaml
 mssql:
    - description: $(database)
      connection: sqlserver://$(username):$(password)@$(host)?database=$(database)
      query: "SELECT 1"
      auth:
        password:
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        host:
          valueFrom:
            secretKeyRef:
              name: db
              key: host

        database:
          valueFrom:
            secretKeyRef:
              name: db
              key: database
        username:
          valueFrom:
            secretKeyRef:
              name: db
              key: username
```
