### ISSUE TITLE
Connection Resource

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#534]
```yaml
kind: Connection
spec:
   url:  EnvVarSource # hostname, url, url with port
   port: EnvVarSource
   type: string
   username: EnvVarSource
   password: EnvVarSource
   certificate: EnvVarSource
   properties: map # e.g. for region
---- 
kind: Canary
spec:
   postgres:
       connection: $(postgres-db)
``` 
- All authentication objects then get a connection, which will be looked up at runtime
- Rename existing usages of connection to url to prevent confusion
- Update all check to support connections
