### ISSUE TITLE
Topology  Property- Link to Config

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#556]
Link topology items to config based on property

```yaml
properties:
- name: vpcId
    value: 123
- name: vpc
   configLookup:
       type: VPC
       id: $.vpcId
       display:
          field: $.tags.name
```
