### ISSUE TITLE
Component - Logs selector

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#569]

**Comment by moshloop** [comment]
In components add a log selector section:

```yaml
logs:
    - name: Elastic
       type: elastic
       labels:
            node: {{.properties.nodeName
```

And then add a logs endpoint in incident commander that mirrors the api from apm-hub,  but  merges in the labels/type into what is submitted by the end user, before forwarding to apm-hub
