### ISSUE TITLE
Create CRD & Controller

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#59]
```yaml
apiVersion: canary.flanksource.com/v1
kind: CanaryCheck
spec:
    interval: 60s
    secretRefs:
        - secrets
    config: #json.rawMessage
```

The controller should update the status for each CRD after each check and fire events for failures, to enable `kubectl get canary` 

We can either deploy a new canary-checker instance per CRD and aggregate results or run all the canaries from the controller,
