### ISSUE TITLE
Add labels for the canary on the metrics tags

### ISSUE THREAD

**Issue by Kaitou786** [flanksource/canary-checker#593]

**Comment by miry** [comment]
I missed this feature as well. It would avoid to create custom metrics and instead of this just add labels to the existing prometheus metrics.

**Comment by moshloop** [comment]
Hi @miry 

Part of the reason we don't do this currently is the potential for an explosion of labels keys and values - Would a whitelist of label keys that get added to `canary_check_info` work ?

**Comment by miry** [comment]
@moshloop I might be misunderstanding the title, but I’m aiming to add a limited number of custom tags to all metrics produced by Canarychecker's probes.

For example:

```
- http:
    ...
    metricsLabels:
      domain: example.com
- http:
    ...
    metricsLabels:
      domain: another.example.com
```

This would allow filtering probe statuses based on those labels:

```
canary_check{domain=another.example.com}
canary_check{domain=example.com}
```

Does this align with the intended functionality, or am I missing something?

I thought to reuse the field `labels` from https://canarychecker.io/reference/http , but it does not add those labels to the metrics.
