### ISSUE TITLE
Postresql SQL execute

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#6]
**Input**
```yaml
connection: user=pqgotest dbname=pqgotest sslmode=verify-full
query:  SELECT 1
results: 1
```

**Output**: Pass/Fail/Invalid

**Metrics**:

* response_time
* Record count (min,max,avg)
