### ISSUE TITLE
Topology  - Incidents query

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#678]
Add includeIncidents option and return a summary of incidents by type and severity.

```yaml
incidents:
  availability:
       high: 1
       med: 1
```
