### ISSUE TITLE
Topology Query - Incidents are not returned

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#686]

**Comment by yashmehrotra** [comment]
@moshloop Incidents are returned in the topology query, they are not queried by default though. You need to add a `includeIncidents=1` query parameter to display them

Example: https://incident-commander.canary.lab.flanksource.com/api/canary/api/topology?id=0183bfe6-806a-7615-6840-590a37517e88&includeIncidents=1

Should I display showing incidents the default behavior ?

**Comment by moshloop** [comment]
@yashmehrotra summary of incidents and insights should be on by default, configs should be off.

Can we also rename it as follows:

```yaml
incidents: [] # includeIncidents
configs: [] # includeConfigs
insights: [] #includeInsights
summary:
   healthy: 1
   unhealthy: 2
   incidents:
      availability:
         high: 1
   insights:
      availability:
         high: 1
```
