### ISSUE TITLE
Config lookup by expression

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#687]
Support arbitrary Templates for property config lookups, 

e.g.  instead of

```yaml
     - name: Version
            headline: true
            configLookup:
              config:
                type: File
                name: Configuration.properties
                labels:
                  namespace: ${.properties.namespace}
              field: $["application.buildversion"]
```

```yaml
   -  name: Version
      template:
          javascript: configs['File/Configuration.properties'].config['application.buildversion']
```

Fields that should be available

* self
* self.properties
* configs ( A map of all related configs with `type/name` key )
*
