### ISSUE TITLE
LDAP lookup / auth

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#7]
**Input**
```yaml
host: ldaps://hostname:636
username: admin
password: admin
bindDn: 
userSearch: 
```

**Output**: Pass/Fail/Invalid

**Metrics**:

* Lookup time
* Record count (min,max,avg)
