### ISSUE TITLE
POD Schedule & Serve

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#8]
Given the pod spec, create a Pod, service and ingress, schedule it and then confirm that it serves results correctly via the ingress

```yaml:
# Full pod spec
spec:
   ....
thresholdMillis: 300
expectedContent: OK

```

Metrics:
* schedule_time (from `Pending` to `ContainerCreating`)
* creation_time (from `ContainerCreatning` to `Running`)
* destroy_time (from `Terminating` to `Terminated`)
* ingress_time (from `Running` to Ingress check succeeds)
* serve_time (Response time via ingress)
