### ISSUE TITLE
Inline checks always take component sync schedule even if schedule is defined in canary spec

### ISSUE THREAD

**Issue by yashmehrotra** [flanksource/canary-checker#916]
```yaml
kind: SystemTemplate
spec:
  schedule: "@every 15m"
  components:
    - name: XYZ
      checks:
        - inline:
           http:
             - name: check-name
               schedule: "@every 1m"
```

The inline check created will always take 15m as it's schedule
