### ISSUE TITLE
Custom metric support

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#953]
i.e. Extract metric values and labels from check details  e.g. enables using any of canary-checker check types to expose metrics e.g.

```
metrics:
- name: canary_check_http_response_status
   type: counter
   labels: 
       status: {{.response.code}}
       statusClass: "{{ .reponse.code | to_string | char_at 0}}xx"
       url: {{.check.url}}
   value: {{ if response.ok }}1{{endif}}
```
