### ISSUE TITLE
Canary scaling subresource

### ISSUE THREAD

**Issue by moshloop** [flanksource/canary-checker#990]
Allow canary objects to be scaled to 0, allowing them to be disabled as part of scale to zero of underlying pods

**Comment by moshloop** [comment]
e.g. to be used with Keda like

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Canary
    name: api
  triggers:
    - type: cron
      metadata:
        start: 0 * * * *
        end: 10 * * * *
        desiredReplicas: 0
```

or via kubectl scale --replicas=0 canary object

It probably makes the most sense to add and remove  `suspend` annotation on the canary in the scale handler, and then support the suspend annotation normally
